spring:
  application:
    name: blue-service
  cloud:
    consul:
      discovery:
        instance-id: ${spring.application.name}.${random.value}
    loadbalancer:
      ribbon:
        enabled: false
server:
  port: 0
management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
